### ISSUE TITLE
Missing certificate generating error at plugin startup

### ISSUE THREAD

**Issue by aklira** [fledge-power/fledge-north-s2opcua#16]
Feb 20 14:31:05 04c641e0fafa Fledge opcua_north_c1[16762]: FATAL: Failed to load north plugin, exiting...

Feb 20 14:31:05 04c641e0fafa Fledge opcua_north_c1[16762]: FATAL: OPC UA server plugin creation failed:std::exception

Feb 20 14:31:05 04c641e0fafa Fledge opcua_north_c1[16762]: FATAL: ASSERT FAILED in /tmp/dev_n_opc/fledge-north-s2opcua/src/opcua_server_config.cpp:185:Missing Server certificate file: /usr/local/fledge/data/etc/certs/s2opc_srv/server/server_2k_cert.der

Feb 20 14:31:05 04c641e0fafa Fledge opcua_north_c1[16762]: INFO: ----------------------------

Feb 20 13:15:34 04c641e0fafa Fledge opcua_north_c1[1396]: FATAL: Failed to load north plugin, exiting...

Feb 20 13:15:34 04c641e0fafa Fledge opcua_north_c1[1396]: FATAL: OPC UA server plugin creation failed:std::exception

Feb 20 13:15:34 04c641e0fafa Fledge opcua_north_c1[1396]: FATAL: ASSERT FAILED in /tmp/dev_n_opc/fledge-north-s2opcua/src/opcua_server_config.cpp:185:Missing Server certificate file: /usr/local/fledge/data/etc/certs/s2opc_srv/server/server_2k_cert.der

Feb 20 13:15:34 04c641e0fafa Fledge opcua_north_c1[1396]: INFO: ----------------------------

**Comment by jchabod** [comment]
You must deploy certificates for your server.


The deployment path for certificates is enforced to `$FLEDGE_INSTALL/data/etc/certs/s2opc_srv/` and must follow the subfolders as given in [samples](https://github.com/fledge-power/fledge-north-s2opcua/tree/main/samples/cert) (You can see that in root `Makefile` for target `install_certs`, which is used in tests)

Obviously **you cannot** reuse certificates provided in samples since they are development-purpose with known public and private keys.

The file names  are to be provided in plugin configuraiton (Section protocol_stack / transport_layer / certificates)

**Comment by aklira** [comment]
Problem solved, thanks.
